default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/api_rails_katas_development

test:
  <<: *default
  database: db/api_rails_katas_test

production:
  <<: *default
  database: db/api_rails_katas_production
